import React, { useState, useEffect } from 'react'
import { generateKeyPair, exportKey } from '../../services/rsa'
import { IdentityCardGenerator } from '../IdentityCardGenerator'
import { GlassCard, GlassButton, TechHeader } from '../ui/GlassComponents'
import { User, Shield, Upload, UserPlus, Trash2 } from 'lucide-react'
import { extract } from '../../services/webStego'

interface Contact {
  name: string
  publicKey: string
  addedAt: number
}

export default function IdentityPanel() {
  const [, setMyKeys] = useState<{ publicKey: CryptoKey; privateKey: CryptoKey } | null>(null)
  const [myPublicKeyPem, setMyPublicKeyPem] = useState<string | null>(null)
  const [contacts, setContacts] = useState<Contact[]>([])

  // Load contacts/keys from local storage on mount
  useEffect(() => {
    const savedContacts = localStorage.getItem('contacts')
    if (savedContacts) {
      setContacts(JSON.parse(savedContacts))
    }

    // Check if we have saved keys (Note: Storing private key in localStorage is not ideal for prod,
    // but for this task/demo/electron-store replacement it suffices or we can use IndexedDB.
    // For now, I'll generate new keys if missing or allow user to regenerate).
    // In a real app, use a secure vault.
  }, [])

  const handleGenerateKeys = async () => {
    const keys = await generateKeyPair()
    setMyKeys(keys)
    const pubPem = await exportKey(keys.publicKey)
    setMyPublicKeyPem(pubPem)

    // Save Private Key to LocalStorage (Encrypted ideally, but raw for now as per scope)
    const privPem = await exportKey(keys.privateKey)
    localStorage.setItem('my_private_key', privPem)
    localStorage.setItem('my_public_key', pubPem)
  }

  const handleImportContact = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    try {
      const buffer = await file.arrayBuffer()
      const data = await extract(buffer)
      const textDecoder = new TextDecoder()
      const publicKey = textDecoder.decode(data)

      if (publicKey.includes('BEGIN PUBLIC KEY')) {
        const name = prompt('Enter a name for this contact:') || 'Unknown Agent'
        const newContact: Contact = { name, publicKey, addedAt: Date.now() }
        const newContacts = [...contacts, newContact]
        setContacts(newContacts)
        localStorage.setItem('contacts', JSON.stringify(newContacts))
        alert('Identity Verified & Contact Added.')
      } else {
        alert('Invalid Identity Card.')
      }
    } catch (err) {
      console.error(err)
      alert('Failed to read Identity Card. Make sure it is a valid PNG generated by this app.')
    }
  }

  const handleDeleteContact = (index: number) => {
    const newContacts = contacts.filter((_, i) => i !== index)
    setContacts(newContacts)
    localStorage.setItem('contacts', JSON.stringify(newContacts))
  }

  // Load keys on startup
  useEffect(() => {
    const pub = localStorage.getItem('my_public_key')
    if (pub) {
      setMyPublicKeyPem(pub)
      // We don't necessarily need to hydrate the CryptoKey object unless we are decrypting right now,
      // but we will need it for decryption later.
      // For this panel, we just need the string to generate the card.
    }
  }, [])

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-10">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-accent-primary to-accent-secondary">
          Digital Identity
        </h2>
        <p className="text-text-secondary">
          Manage your cryptographic identity and verified contacts.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* My Identity Section */}
        <GlassCard className="space-y-6">
          <TechHeader title="My Clearance Card" icon={<User size={18} />} />

          {myPublicKeyPem ? (
            <IdentityCardGenerator
              publicKey={myPublicKeyPem}
              onRegenerate={handleGenerateKeys}
            />
          ) : (
            <div className="flex flex-col items-center justify-center h-[300px] border-2 border-dashed border-white/10 rounded-xl gap-4">
              <Shield size={48} className="text-white/20" />
              <p className="text-text-secondary text-center max-w-xs">
                No identity detected. Generate a secure RSA keypair to create your Access Card.
              </p>
              <GlassButton onClick={handleGenerateKeys} icon={<Shield size={16} />}>
                Generate Identity
              </GlassButton>
            </div>
          )}
        </GlassCard>

        {/* Contacts Section */}
        <GlassCard className="space-y-6 flex flex-col h-full">
          <div className="flex justify-between items-center">
            <TechHeader title="Known Associates" icon={<UserPlus size={18} />} />
            <div className="relative">
              <input
                type="file"
                accept="image/png"
                onChange={handleImportContact}
                className="absolute inset-0 opacity-0 cursor-pointer"
              />
              <GlassButton size="sm" icon={<Upload size={14} />}>
                Import Card
              </GlassButton>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto space-y-3 max-h-[400px] pr-2 custom-scrollbar">
            {contacts.length === 0 ? (
              <div className="text-center text-text-secondary/50 py-10 italic">
                No contacts verified. Import an Identity Card to begin secure comms.
              </div>
            ) : (
              contacts.map((contact, idx) => (
                <div
                  key={idx}
                  className="bg-black/20 border border-white/5 rounded-lg p-3 flex items-center justify-between group hover:border-accent-primary/30 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-accent-primary/20 to-accent-secondary/20 flex items-center justify-center text-accent-primary font-bold">
                      {contact.name.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <div className="font-bold text-sm">{contact.name}</div>
                      <div className="text-[10px] text-text-secondary font-mono">
                        {contact.publicKey.substring(30, 50)}...
                      </div>
                    </div>
                  </div>
                  <button
                    onClick={() => handleDeleteContact(idx)}
                    className="p-2 text-text-secondary hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <Trash2 size={16} />
                  </button>
                </div>
              ))
            )}
          </div>
        </GlassCard>
      </div>
    </div>
  )
}
